account/urls.py
from django.urls import path
from . import views 
app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("verify-email/<slug:username>", views.verify_email, name="verify-email"),
    path("verify-email/<slug:username>/<uidb64>/", views.auto_active_verify_email, name="auto_verify-email"),
    path("resend-otp", views.resend_otp, name="resend-otp"),
    
]

automation_dj/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    path('dataentry/', include('dataentry.urls')),
    path('celery-test/', views.celery_test),
    path('emails/', include('emails.urls')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('image-compression/', include('image_compression.urls')),
    path('webscraping/', include('stockanalysis.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

emails/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('send-email/', views.send_email, name='send_email'),
    path('track/click/<unique_id>/', views.track_click, name='track_click'),
    path('track/open/<unique_id>/', views.track_open, name='track_open'),
    path('track/dashboard/', views.track_dashboard, name='track_dashboard'),
    path('track/stats/<int:pk>/', views.track_stats, name='track_stats'),
]

templates/alerts.html
<style>
/* Custom close button inside alert */
.custom-close-btn {
    background: transparent;
    border: none;
    font-size: 1.2rem;
    font-weight: bold;
    color: #555;           /* subtle gray color */
    cursor: pointer;
    transition: color 0.3s ease;
    margin-left: 10px;
}

.custom-close-btn:hover {
    color: #d33;           /* red on hover */
}
</style>


{% if messages %}
<div class="messages" id="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible d-flex justify-content-between align-items-center">
        <span>{{ message }}</span>
        <!-- Cross button -->
        <button type="button" class="custom-close-btn" onclick="this.parentElement.style.display='none';">&times;</button>
        {% comment %} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> {% endcomment %}
    </div>
    {% endfor %}
</div>
{% endif %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Automate The Boring Stuff With Django</title>

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

    <!-- JQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    
    <script src="{% static 'js/custom.js' %}"></script>

    <!-- CKEditor Scripts -->
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <style>
      .form-group{
        padding: 15px !important;
      }
      .home-info{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 20px;
      }
    </style>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Automate With Django</a>
          
          {% if user.is_authenticated %}
          <!-- show logout button -->
          <div>
            Logged in as: <b>{{ user }}</b>
            &nbsp;<a href="{% url 'account:logout' %}" class="float-right btn btn-outline-danger">Logout</a>
          </div>
          {% else %}
          <div>
            <a href="{% url 'account:login' %}" class="float-right text-decoration-none text-dark">Login</a>
            &nbsp;<a href="{% url 'account:register' %}" class="float-right btn btn-success">Register</a>
          </div>
          {% endif %}
        </div>
    </nav> 

    {% block content %}
        <!-- All your html main content will go here -->
    {% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container" style="padding: 50px;margin-top: 5%;">
    {% if user.is_authenticated %}
    <h2 class="text-center">Smart Django Tools</h2>
    <div class="row pt-5">
        <!-- Import data -->
        <div class="col-md-4">
            <a href="{% url 'import_data' %}" class="text-decoration-none text-dark">
                <div class="card alert-primary shadow">
                    <div class="card-header">
                    <h4>Import Data</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Imports data from CSV file to any table.</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Export Data -->
        <div class="col-md-4">
            <a href="{% url 'export_data' %}" class="text-decoration-none text-dark">
                <div class="card alert-success shadow">
                    <div class="card-header">
                    <h4>Export Data</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Exports data from a specific table to a CSV file.</p>
                    </div>
                </div>
            </a>
        </div>

        <!-- Bulk Emails -->
        <div class="col-md-4">
            <a href="{% url 'send_email' %}" class="text-decoration-none text-dark">
            
                <div class="card alert-danger shadow">
                    <div class="card-header">
                    <h4>Bulk Emails</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Sends bulk emails to users</p>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="row pt-5">
        <!-- Email Tracking -->
        <div class="col-md-4">
            <a href="{% url 'track_dashboard' %}" class="text-decoration-none text-dark">
                <div class="card alert-warning shadow">
                    <div class="card-header">
                    <h4>Email Tracking</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Tracks emails and shows open and click rate</p>
                    </div>
                </div>
            </a>
        </div>
        <!-- Compress Images -->
        <div class="col-md-4">
            <a href="{% url 'compress' %}" class="text-decoration-none text-dark">
                <div class="card alert-danger shadow">
                    <div class="card-header">
                    <h4>Compress Images</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Compresses Image files and reduces the size</p>
                    </div>
                </div>
            </a>
        </div>

        <!-- Web Scraping -->
        <div class="col-md-4">
            <a href="{% url 'stocks' %}" class="text-decoration-none text-dark">
                <div class="card alert-warning shadow">
                    <div class="card-header">
                    <h4>Stock Market Analysis</h4>
                    </div>
                    <div class="card-body">
                    <p class="card-text">Stock Market Analysis - Web Scraping</p>
                    </div>
                </div>
            </a>
        </div>
    </div>

    
    {% else %}

    <div class="home-info">
        <h2 class="text-center">Automate the Boring Stuff with Django</h2>
        <p class="lead text-center text-muted">
            "Automate the Boring Stuff with Django" is a project-based course to build various tools using the Django framework to automate routine tasks, ranging from data processing to scheduling, and more. 
            By leveraging Django's capabilities, users can streamline their workflows, saving time and enhancing productivity.
        </p>

        <div style="display: flex; justify-content: center;">
            <a href="{% url 'account:login' %}" class="btn btn-primary">LOGIN</a>
            &nbsp;<a href="{% url 'account:register' %}" class="btn btn-success">REGISTER</a>
        </div>
    </div>

    {% endif %}

</div>
{% endblock %}